# autostart your favorite applications here

# required for dms as systemd service
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start mango-session.target


exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = steam -silent
exec-once = swayidle -w
exec-once = bitwarden