# autostart your favorite applications here

# required for dms as systemd service
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start mango-session.target

# apps
exec-once = bash -c wl-paste --watch cliphist store &  # optional: clipboard history | cliphist is needed
exec-once = steam -silent
exec-once = swayidle -w
