# autostart your favorite applications here

exec-once = dms run &
exec-once = bash -c wl-paste --watch cliphist store &  # optional: clipboard history | cliphist is needed
exec-once = steam -silent
exec-once = swayidle -w