# | Layout |
# layouts | https://mangowm.github.io/docs/window-management/layouts

# Scrolling layout settings.
scroller_structs = 30
scroller_default_proportion = 0.5
scroller_focus_center = 0
scroller_prefer_center = 0p
scroller_prefer_overspread = 1
edge_scroller_pointer_focus = 1
scroller_default_proportion_single = 2.0
scroller_proportion_preset = 0.5, 0.8, 1.0

# Master-Stack layout settings.
new_is_master = 1
default_mfact = 0.55
default_nmaster = 1
smartgaps = 0


# https://mangowm.github.io/docs/configuration/miscellaneous

allow_tearing = 1
# syncobj_enable = 1
# xwayland-persistence = 1

drag_tile_to_tile = 1
