# | Outputs Configuration |
# Configure your monitors here or in the DMS "Displays" settings. | https://mangowm.github.io/docs/configuration/monitors
# Run `wlr-randr` to get your monitors information.
# You will have to remove "#" and edit it for it to take effect.
#monitorrule = name:DP-1, width:2560, height:1440, refresh:179.999, x:0, y:0, rr:0, vrr:1

# Change your layout here for each workspace.
# tile, scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller
tagrule = id:1, layout_name:scroller   
tagrule = id:2, layout_name:tile
tagrule = id:3, layout_name:center_tile
tagrule = id:4, layout_name:tile
tagrule = id:5, layout_name:tile
tagrule = id:6, layout_name:tile
tagrule = id:7, layout_name:tile
tagrule = id:8, layout_name:tile
tagrule = id:9, layout_name:tile