# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

windowrule = isfloating:1, appid:[Ss]team
windowrule = isfloating:0, title:Steam
windowrule = isfloating:1, appid:steam, title:Steam Settings
windowrule = isfloating:1, title:Bitwarden

layerrule = noanim:1, noblur:1, layer_name:selection