# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, N, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp $webapp_calendar
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp $webapp_email
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-webapp $webapp_mmusic

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Replace window swap with window move
unbind = SUPER SHIFT, LEFT,
unbind = SUPER SHIFT, RIGHT,
unbind = SUPER SHIFT, UP,
unbind = SUPER SHIFT, DOWN,

bindd = SUPER SHIFT, LEFT, Move active window to the left, movewindow, l
bindd = SUPER SHIFT, RIGHT, Move active window to the right, movewindow, r
bindd = SUPER SHIFT, UP, Move active window upwards, movewindow, u
bindd = SUPER SHIFT, DOWN, Move active window downwards, movewindow, d

