preload=/home/ngeorg/Pictures/wallpaper_1920x1200.png
preload=/home/ngeorg/Pictures/inits_wallpaper.png
wallpaper = , /home/ngeorg/Pictures/wallpaper_1920x1200.png
wallpaper = desc:Lenovo Group Limited R45w-30 UPP06G9F , /home/ngeorg/Pictures/inits_wallpaper.png
