# my configs based on cachyos defaults
source=~/.config/mango/configs/autostart.conf
source=~/.config/mango/configs/env.conf
source=~/.config/mango/configs/input.conf
source=~/.config/mango/configs/keybinds.conf
source=~/.config/mango/configs/layout.conf
source=~/.config/mango/configs/outputs.conf
source=~/.config/mango/configs/theming.conf
source=~/.config/mango/configs/rules.conf

# DankMaterialShell
# https://github.com/AvengeMedia/DankMaterialShell
source=~/.config/mango/dms/colors.conf
source=~/.config/mango/dms/layout.conf
source=~/.config/mango/dms/outputs.conf
source=~/.config/mango/dms/cursor.conf
source=~/.config/mango/dms/binds.conf
