#!/bin/bash

MODE="$1"
case "$MODE" in
  a|A|wide)
    # Setup A: Single ultrawide monitor
    hyprctl dispatch dpms off HDMI-A-1
    hyprctl keyword monitor "DP-1, 5120x1440@165, 0x0, 1"
    hyprctl keyword monitor "HDMI-A-1, disable"  
  ;;

  b|B|dual)
    # Setup B: Dual monitors
    hyprctl keyword monitor "DP-1, 2560x1440@120, 0x0, 1"
    hyprctl keyword monitor "HDMI-A-1, 2560x1440@120, 2560x0, 1"
    ;;

  *)
    echo "Usage: $0 [a|b]"
    echo "  a / wide - Setup A: 5120x1440@165 on DP-1"
    echo "  b / dual - Setup B: 2560x1440@120 on DP-1 and HDMI-A-1"
    exit 1
    ;;
esac
